rbac:
  create: false

nameOverride: ""
fullnameOverride: ""
# register prefix
registerPre: "arexadmin01/"
# mongodb config demo
mongoInfo: "mongodb://arex:iLoveArex@10.5.153.1:27017/arex_storage_db"
# redis config demo
redisInfo: "redis://10.5.153.1:6390/"

front:
  enabled: true
  name: ui
  image:
    repository: arex
    tag: 0.2.9
    pullPolicy: IfNotPresent

  serviceAcountName: default
  extraArgs: {}
  prefixURL: ""
  baseURL: ""

  replicaCount: 1
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    externalIPs: []

    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 8080
    type: ClusterIP

  ingress:
    enabled: true
    annotations: {}
    hosts: ["local.arextest.com"]
    tls: ""

  resources: {}
  nodeSelector: {}
  podAnnotations: {}
  tolerations: {}

storage:
  enabled: true
  name: storage
  image:
    repository: arex-storage-serive
    tag: 0.2.9
    pullPolicy: IfNotPresent
  serviceAcountName: default
  extraArgs: {}
  prefixURL: ""
  baseURL: ""
  replicaCount: 1
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 8080
    type: ClusterIP
  resources: {}
  nodeSelector: {}
  podAnnotations: {}
  tolerations: {}

report:
  enabled: true
  name: report
  image:
    repository: arex-report
    tag: 0.2.9
    pullPolicy: IfNotPresent

  serviceAcountName: default
  extraArgs: {}
  prefixURL: ""
  baseURL: ""

  replicaCount: 1
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    externalIPs: []

    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 8080
    type: ClusterIP

  resources: {}
  nodeSelector: {}
  podAnnotations: {}
  tolerations: {}

schedule:
  enabled: true
  name: schedule
  image:
    repository: arex-replay-schedule
    tag: 0.2.9
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    externalIPs: []

    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 8080
    type: ClusterIP

  nodeSelector: {}
  podAnnotations: {}
  tolerations: {}
  resources: {}

mongodb:
  enabled: true
  name: mongodb
  storage: 5Gi
  image:
    repository: mongo
    tag: 5.0
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    externalIPs: []

    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 27017
    type: ClusterIP

  nodeSelector: {}
  podAnnotations: {}
  tolerations: {}
  resources: {}

redis:
  enabled: true
  name: redis
  storage: 1Gi
  image:
    repository: redis
    tag: 6.2.6
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    externalIPs: []

    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 6379
    type: ClusterIP

  nodeSelector: {}
  podAnnotations: {}
  tolerations: {}
  resources: {}
